# Generated by Django 3.1.2 on 2020-10-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201012_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='user',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='files',
            field=models.ManyToManyField(to='core.Attachment'),
        ),
    ]
