# Generated by Django 3.1.2 on 2020-10-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_attachment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='user',
        ),
    ]
