# Generated by Django 3.1.2 on 2020-10-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_attachment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='title',
            field=models.CharField(default='Treatment', max_length=90),
        ),
    ]
