# Generated by Django 3.1.2 on 2020-10-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_treatment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='filename',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
