# Generated by Django 3.1.2 on 2020-10-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_attachment_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(default='filename', max_length=120),
        ),
    ]
