# Generated by Django 3.1.2 on 2020-10-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201016_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(max_length=120),
        ),
    ]
