# Generated by Django 3.1.2 on 2020-10-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201023_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='files',
            field=models.ManyToManyField(to='core.Attachment'),
        ),
    ]
