# Generated by Django 3.1.2 on 2020-10-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201027_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comingtreatment'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='has_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
