# Generated by Django 3.1.2 on 2020-10-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201027_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comingtreatment',
            options={},
        ),
        migrations.RemoveField(
            model_name='currentpatients',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
