# Generated by Django 3.1.2 on 2020-11-27 15:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201127_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='uploads/product/4edc7b2c-0f96-4fb6-a8bc-22a61e47cd6f.png', upload_to=core.models.product_image_file_path),
        ),
    ]
