# Generated by Django 3.1.2 on 2020-11-27 15:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201127_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.product_image_file_path),
        ),
    ]
