# Generated by Django 3.1.2 on 2021-01-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_treatmenttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmenttemplate',
            name='module',
            field=models.CharField(choices=[('Appointment', 'Appointment'), ('Treatment', 'Treatment'), ('Operation', 'Operation')], default='Treatment', max_length=20),
        ),
    ]
